language: node_js
node_js:
  - "5.10.1"
env:
  global:
    secure: oIXzNp7o4Hi8y+TU9Ur9HIRC5lEjioYc19eXJi0ilgEV8Gr3snK73rVEczuaCLA/vh3IUEApslVdSpawgHeQqPu2adWXfo424Azq10f2t0t8qtIXQZuj8B4m+UdYZVE7Zz9ez57JvucEsyPf8b06xJ5pOvR1v01WonbIQyEja9vSRaNk1lz1+Upa33wJAA6WREtLVEsn5vnQf8S6DxyboiY1cil4XIirVRuESFTnsq8qG9jwfvf2O0W5SAZpT2k5XHwBDEB9LtBDMQ09W6KvOrOr5gFtzcCoEhcCclnRjtooAUsvyxE7B4tDtAQoK9B4wIQxFIn2hb0rkjSE/3P3LXBTzODb1oWfnyqC3uOkOMdCd5L6tNH5vgB2ZEnkieipgG8cw7ORMueK5HTM3M+9KbQDaKY1SsjEg/CwOAXmdQNhbrFSZwXcyzKvbBdWTXbcqA4hpbpkdzD8wDsh2QNF4Ar59ZmzHEP9h6dkPgcQMUVEI93ATBDz5H/CjdcISa6RSjoE6zzrRTyWHhRBmC6na9AVtKIJQxfUAyi/M5OeBX8TxKQF6OnBU4b1irYBb9NbVbAef8EO4Ks7RQyja+86u5as/ZhOLfg917u8GILU3YJVtqHwhckKdJT6OCifSO2iI6Jzx1FFBlYSpbVxZN/xoFWnXI057DBkAEiGMIFeqPs=

script:
  - npm install -g git-credential-env
  - git config credential.helper "env --username=GITHUB_TOKEN"
  - git config user.name "Travis CI"
  - npm run deploy
